//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDiagramSample.Module.BusinessObjects.DiagramTest
{

    public partial class MonitoringBoard : XPObject
    {
        Guid fGuid;
        public Guid Guid
        {
            get { return fGuid; }
            set { SetPropertyValue<Guid>(nameof(Guid), ref fGuid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        [Association(@"ProcessingNodeReferencesMonitoringBoard")]
        public XPCollection<ProcessingNode> ProcessingNodes { get { return GetCollection<ProcessingNode>(nameof(ProcessingNodes)); } }
    }

}
