//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDiagramSample.Module.BusinessObjects.DiagramTest
{

    public partial class ProcessingFlowOutput : XPObject
    {
        ProcessingNode fOutputFromNode;
        [Association(@"ProcessingFlowOutputReferencesProcessingNode")]
        public ProcessingNode OutputFromNode
        {
            get { return fOutputFromNode; }
            set { SetPropertyValue<ProcessingNode>(nameof(OutputFromNode), ref fOutputFromNode, value); }
        }
    }

}
