//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDiagramSample.Module.BusinessObjects.DiagramTest
{

    public partial class ProcessingNode : XPObject
    {
        Guid fGuid;
        public Guid Guid
        {
            get { return fGuid; }
            set { SetPropertyValue<Guid>(nameof(Guid), ref fGuid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        MonitoringBoard fMonitoringBoard;
        [Association(@"ProcessingNodeReferencesMonitoringBoard")]
        public MonitoringBoard MonitoringBoard
        {
            get { return fMonitoringBoard; }
            set { SetPropertyValue<MonitoringBoard>(nameof(MonitoringBoard), ref fMonitoringBoard, value); }
        }
        float fPositionX;
        public float PositionX
        {
            get { return fPositionX; }
            set { SetPropertyValue<float>(nameof(PositionX), ref fPositionX, value); }
        }
        float fPositionY;
        public float PositionY
        {
            get { return fPositionY; }
            set { SetPropertyValue<float>(nameof(PositionY), ref fPositionY, value); }
        }
        float fWidth;
        [ColumnDefaultValue(100)]
        public float Width
        {
            get { return fWidth; }
            set { SetPropertyValue<float>(nameof(Width), ref fWidth, value); }
        }
        float fHeight;
        [ColumnDefaultValue(50)]
        public float Height
        {
            get { return fHeight; }
            set { SetPropertyValue<float>(nameof(Height), ref fHeight, value); }
        }
        [Association(@"ProcessingFlowOutputReferencesProcessingNode")]
        public XPCollection<ProcessingFlowOutput> OutputFlows { get { return GetCollection<ProcessingFlowOutput>(nameof(OutputFlows)); } }
        [Association(@"ProcessingFlowInputReferencesProcessingNode")]
        public XPCollection<ProcessingFlowInput> InputFlows { get { return GetCollection<ProcessingFlowInput>(nameof(InputFlows)); } }
    }

}
