//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDiagramSample.Module.BusinessObjects.DiagramTest
{

    public partial class ProcessingFlow : XPObject
    {
        string fFlowType;
        public string FlowType
        {
            get { return fFlowType; }
            set { SetPropertyValue<string>(nameof(FlowType), ref fFlowType, value); }
        }
        Guid fGuid;
        public Guid Guid
        {
            get { return fGuid; }
            set { SetPropertyValue<Guid>(nameof(Guid), ref fGuid, value); }
        }
    }

}
